version: '3.8'

services:
  redis:
    image: redis:latest
    volumes:
      - redis:/data
    ports:
      - '6379:6379'

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ascend123
      POSTGRES_DB: db01
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  redis:
    driver: local
  postgres:
    driver: local
